In [10]:
import pandas as pd
import pickle

In [11]:
tt = pickle.load(open('summary_QpxQpy1_b3b5b7_270GeV_ayyScan_axyNoConstraint_LOD.pkl', 'rb'))

In [12]:
tt

,ayy [1/m],axy [1/m],klof [1/m^4],klod [1/m^4],O3_lof [T/m^3],O3_lod [T/m^3],I_lof [A],I_lod [A]
0,-3.386528e-10,-454.713692,0.0,0.047905,0.0,43.144168,0.0,0.431442
1,-2.000000e+03,543.957381,0.0,-1.834088,0.0,-1651.821641,0.0,-16.518216
2,-4.000000e+03,1542.628453,0.0,-3.716080,0.0,-3346.787450,0.0,-33.467875
3,-6.000000e+03,2541.299525,0.0,-5.598073,0.0,-5041.753259,0.0,-50.417533
4,-8.000000e+03,3539.970598,0.0,-7.480065,0.0,-6736.719068,0.0,-67.367191
5,-1.000000e+04,4538.641670,0.0,-9.362058,0.0,-8431.684877,0.0,-84.316849
6,-1.200000e+04,5537.312742,0.0,-11.244050,0.0,-10126.650686,0.0,-101.266507
7,-1.400000e+04,6535.983815,0.0,-13.126042,0.0,-11821.616495,0.0,-118.216165
8,-1.600000e+04,7534.654887,0.0,-15.008035,0.0,-13516.582304,0.0,-135.165823
9,-1.800000e+04,8533.325959,0.0,-16.890027,0.0,-15211.548113,0.0,-152.115481
10,-2.000000e+04,9531.997032,0.0,-18.772020,0.0,-16906.513922,0.0,-169.065139
11,-3.386528e-10,-454.713692,0.0,0.047905,0.0,43.144168,0.0,0.431442
12,2.000000e+03,-1453.384764,0.0,1.929897,0.0,1738.109977,0.0,17.381100
13,4.000000e+03,-2452.055836,0.0,3.811890,0.0,3433.075786,0.0,34.330758
14,6.000000e+03,-3450.726909,0.0,5.693882,0.0,5128.041595,0.0,51.280416
15,8.000000e+03,-4449.397981,0.0,7.575875,0.0,6823.007404,0.0,68.230074
16,1.000000e+04,-5448.069053,0.0,9.457867,0.0,8517.973212,0.0,85.179732
17,1.200000e+04,-6446.740126,0.0,11.339860,0.0,10212.939021,0.0,102.129390
18,1.400000e+04,-7445.411198,0.0,13.221852,0.0,11907.904830,0.0,119.079048
19,1.600000e+04,-8444.082270,0.0,15.103845,0.0,13602.870639,0.0,136.028706
20,1.800000e+04,-9442.753343,0.0,16.985837,0.0,15297.836448,0.0,152.978364
21,2.000000e+04,-10441.424415,0.0,18.867829,0.0,16992.802257,0.0,169.928023

In [13]:
tt['ayy [1/m]']

0    -3.386528e-10
1    -2.000000e+03
2    -4.000000e+03
3    -6.000000e+03
4    -8.000000e+03
5    -1.000000e+04
6    -1.200000e+04
7    -1.400000e+04
8    -1.600000e+04
9    -1.800000e+04
10   -2.000000e+04
11   -3.386528e-10
12    2.000000e+03
13    4.000000e+03
14    6.000000e+03
15    8.000000e+03
16    1.000000e+04
17    1.200000e+04
18    1.400000e+04
19    1.600000e+04
20    1.800000e+04
21    2.000000e+04
Name: ayy [1/m], dtype: float64

In [9]:
tt['ayy [1/m]'][0]

[-3.3865281417414116e-10,
 -1999.999999999903,
 -3999.999999999329,
 -5999.999999999446,
 -8000.00000000063,
 -9999.999999999789,
 -11999.999999999898,
 -13999.999999999509,
 -15999.999999999556,
 -17999.999999999975,
 -19999.999999999232,
 -3.3865281417414116e-10,
 1999.9999999998645,
 3999.9999999993233,
 6000.000000000394,
 7999.9999999998745,
 9999.999999999407,
 11999.999999999467,
 14000.000000000076,
 16000.000000000671,
 18000.00000000023,
 19999.999999999196]